//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by windirstat.rc
//

#define IDC_ADD_CLEANUP                 1000
#define IDC_ADD_FOLDER                  1001
#define IDC_ASKFORCONFIRMATION          1002
#define IDC_AUTO_ELEVATE                1003
#define IDC_BACKUP_RESTORE              1004
#define IDC_BRIGHTNESS                  1005
#define IDC_BROWSE_BUTTON               1006
#define IDC_BROWSE_FOLDER               1007
#define IDC_CAPTION                     1008
#define IDC_CLOUD_LINKS_WARNING         1009
#define IDC_COLORBUTTON0                1010
#define IDC_COLORBUTTON1                1011
#define IDC_COLORBUTTON2                1012
#define IDC_COLORBUTTON3                1013
#define IDC_COLORBUTTON4                1014
#define IDC_COLORBUTTON5                1015
#define IDC_COLORBUTTON6                1016
#define IDC_COLORBUTTON7                1017
#define IDC_COLUMN_AUTOSIZE             1018
#define IDC_COMBO                       1019
#define IDC_COMBO_THREADS               1020
#define IDC_COMMANDLINE                 1021
#define IDC_CONTEXT_MENU                1022
#define IDC_CUSHIONSHADING              1023
#define IDC_DARK_MODE_DISABLED          1024
#define IDC_DARK_MODE_ENABLED           1025
#define IDC_DARK_MODE_USE_WINDOWS       1026
#define IDC_DELETION_BIN_WARNING        1027
#define IDC_DELETION_WARNING            1028
#define IDC_DOWN                        1029
#define IDC_ELEVATION_PROMPT            1030
#define IDC_ENABLED                     1031
#define IDC_EXCLUDE_DROPBOX_IGNORED     1032
#define IDC_EXCLUDE_HIDDEN_DIRECTORY    1033
#define IDC_EXCLUDE_HIDDEN_FILE         1034
#define IDC_EXCLUDE_JUNCTIONS           1035
#define IDC_EXCLUDE_PROTECTED_DIRECTORY 1036
#define IDC_EXCLUDE_PROTECTED_FILE      1037
#define IDC_EXCLUDE_SYMLINKS_DIRECTORY  1038
#define IDC_EXCLUDE_SYMLINKS_FILE       1039
#define IDC_EXCLUDE_VOLUME_MOUNT_POINTS 1040
#define IDC_FAST_SCAN_CHECKBOX          1041
#define IDC_FILTERING_EXCLUDE_DIRS      1042
#define IDC_FILTERING_EXCLUDE_FILES     1043
#define IDC_FILTERING_INCLUDE_DIRS      1044
#define IDC_FILTERING_INCLUDE_FILES     1045
#define IDC_FILTERING_MAX_AGE_COMPARISON 1046
#define IDC_FILTERING_MAX_AGE_DAYS      1047
#define IDC_FILTERING_MIN_UNITS         1048
#define IDC_FILTERING_SIZE_COMPARISON   1049
#define IDC_FILTERING_SIZE_MIN          1050
#define IDC_FILTERING_USE_REGEX         1051
#define IDC_FILTER_BUTTON               1052
#define IDC_FOLDER_HISTORY_COUNT        1053
#define IDC_FULL_ROW_SELECTION          1054
#define IDC_HASH_ALGORITHM              1055
#define IDC_HEIGHT                      1056
#define IDC_HELPBUTTON                  1057
#define IDC_HINTSN                      1058
#define IDC_HINTSP                      1059
#define IDC_KDIRSTAT                    1060
#define IDC_LARGEST_FILE_COUNT          1061
#define IDC_LIGHTSOURCE                 1062
#define IDC_LIST                        1063
#define IDC_MESSAGE_BUTTONLEFT          1064
#define IDC_MESSAGE_BUTTONMIDDLE        1065
#define IDC_MESSAGE_BUTTONRIGHT         1066
#define IDC_MESSAGE_CHECKBOX            1067
#define IDC_MESSAGE_ICON                1068
#define IDC_MESSAGE_LISTVIEW            1069
#define IDC_MESSAGE_TEXT                1070
#define IDC_PACMANANIMATION             1071
#define IDC_PERMS_ACCOUNT0              1072
#define IDC_PERMS_ACCOUNT1              1073
#define IDC_PERMS_ACCOUNT2              1074
#define IDC_PERMS_ACCOUNT3              1075
#define IDC_PERMS_ACCOUNT4              1076
#define IDC_PERMS_EXCLUDE               1077
#define IDC_PERMS_LEVEL0                1078
#define IDC_PERMS_LEVEL1                1079
#define IDC_PERMS_LEVEL2                1080
#define IDC_PERMS_LEVEL3                1081
#define IDC_PERMS_LEVEL4                1082
#define IDC_PORTABLE_MODE               1083
#define IDC_PREVIEW                     1084
#define IDC_PROCESS_HARDLINKS           1085
#define IDC_PROCESS_PRIORITY            1086
#define IDC_PROGRESS_BAR                1087
#define IDC_PROGRESS_MESSAGE            1088
#define IDC_PROMPT_EMPTY_BIN            1089
#define IDC_PROMPT_CREATE_HARDLINK      1090
#define IDC_PROMPT_REMOVE_MOTW          1091
#define IDC_PROMPT_DISABLE_HIBERNATE    1092
#define IDC_PROMPT_REMOVE_SHADOW        1093
#define IDC_PROMPT_DISM_NORMAL          1094
#define IDC_PROMPT_DISM_RESET           1095
#define IDC_PROMPT_SET_DATES            1096
#define IDC_PROMPT_REMOVE_EMPTY         1097
#define IDC_RADIO_TARGET_DRIVES_ALL     1098
#define IDC_RADIO_TARGET_DRIVES_SUBSET  1099
#define IDC_RADIO_TARGET_FOLDER         1100
#define IDC_RECOVERY_BROWSE             1101
#define IDC_RECOVERY_DEST               1102
#define IDC_RECOVERY_DEST_LABEL         1103
#define IDC_RECOVERY_FILTER             1104
#define IDC_RECOVERY_LIST               1105
#define IDC_RECOVERY_PAUSE              1106
#define IDC_RECOVERY_PLAY               1107
#define IDC_RECOVERY_PROGRESS           1108
#define IDC_RECOVERY_RECOVER            1109
#define IDC_RECOVERY_REGEX              1110
#define IDC_RECOVERY_SOURCE             1111
#define IDC_RECOVERY_STOP               1112
#define IDC_RECURSEINTOSUBDIRECTORIES   1113
#define IDC_REFRESHPOLICY               1114
#define IDC_REMOVE_CLEANUP              1115
#define IDC_RESET_PREFERENCES           1116
#define IDC_SAMPLE_LARGE_FILES          1117
#define IDC_SCALEFACTOR                 1118
#define IDC_SCAN_DUPLICATES             1119
#define IDC_SEARCH_CASE                 1120
#define IDC_SEARCH_FILES                1121
#define IDC_SEARCH_FOLDERS              1122
#define IDC_SEARCH_OWNER                1123
#define IDC_SEARCH_PHYSICAL_LABEL       1124
#define IDC_SEARCH_PHYSICAL_MAX         1125
#define IDC_SEARCH_PHYSICAL_MIN         1126
#define IDC_SEARCH_PHYSICAL_SEPARATOR   1127
#define IDC_SEARCH_PHYSICAL_UNITS       1128
#define IDC_SEARCH_REGEX                1129
#define IDC_SEARCH_SIZE_LABEL           1130
#define IDC_SEARCH_SIZE_MAX             1131
#define IDC_SEARCH_SIZE_MIN             1132
#define IDC_SEARCH_SIZE_SEPARATOR       1133
#define IDC_SEARCH_SIZE_UNITS           1134
#define IDC_SEARCH_TERM                 1135
#define IDC_SEARCH_WHOLE_PHRASE         1136
#define IDC_SEQUOIAVIEW                 1137
#define IDC_SHOWCONSOLEWINDOW           1138
#define IDC_SHOWTIMESPENT               1139
#define IDC_SHOW_GRID                   1140
#define IDC_SHOW_MICROSOFT_PROGRESS     1141
#define IDC_SHOW_STRIPES                1142
#define IDC_SHOW_TIME_SECONDS           1143
#define IDC_SIZEGRIPPER                 1144
#define IDC_SIZE_SUFFIXES               1145
#define IDC_SKIP_CLOUD_LINKS            1146
#define IDC_SLIDER                      1147
#define IDC_STATICBRIGHTNESS            1148
#define IDC_STATICCUSHIONSHADING        1149
#define IDC_STATICHEIGHT                1150
#define IDC_STATICSCALEFACTOR           1151
#define IDC_TAB                         1152
#define IDC_TARGET_DRIVES_LIST          1153
#define IDC_TITLE                       1154
#define IDC_TREECOL_ATTRIBUTES          1155
#define IDC_TREECOL_FILES               1156
#define IDC_TREECOL_FOLDERS             1157
#define IDC_TREECOL_ITEMS               1158
#define IDC_TREECOL_LAST_CHANGE         1159
#define IDC_TREECOL_OWNER               1160
#define IDC_TREECOL_PERCENTAGE          1161
#define IDC_TREECOL_SIZE_LOGICAL        1162
#define IDC_TREECOL_SIZE_PHYSICAL       1163
#define IDC_TREEMAPGRID                 1164
#define IDC_TREEMAPGRIDCOLOR            1165
#define IDC_TREEMAPHIGHLIGHTCOLOR       1166
#define IDC_TREEMAPPRESET               1167
#define IDC_TREEMAPSTYLE                1168
#define IDC_UP                          1169
#define IDC_USE_WINDOWS_LOCALE          1170
#define IDC_WAITFORCOMPLETION           1171
#define IDC_WORKSFORDIRECTORIES         1172
#define IDC_WORKSFORDRIVES              1173
#define IDC_WORKSFORFILES               1174
#define IDC_WORKSFORUNCPATHS            1175

#define IDD_ABOUTBOX                    100
#define IDD_MESSAGEBOX                  101
#define IDD_PAGE_ADVANCED               102
#define IDD_PAGE_CLEANUPS               103
#define IDD_PAGE_FILTERING              104
#define IDD_PAGE_GENERAL                105
#define IDD_PAGE_PERMISSIONS            106
#define IDD_PAGE_PROMPTS                107
#define IDD_PAGE_TREELIST               108
#define IDD_PAGE_TREEMAP                109
#define IDD_PROGRESS                    110
#define IDD_RECOVERY                    111
#define IDD_SEARCH                      112
#define IDD_SELECTDRIVES                113

#define IDR_LANGS                       114
#define IDR_LICENSE                     115
#define IDR_MAINFRAME                   116
#define IDR_POPUP_MAP                   117
#define IDR_POPUP_TREE                  118

#define IDS_APP_TITLE                   57344
#define IDS_AUTHOR_EMAIL                57345
#define IDS_FILTER_EXAMPLE_DIRS         57346
#define IDS_FILTER_EXAMPLE_DIRS_REGEX   57347
#define IDS_FILTER_EXAMPLE_FILES        57348
#define IDS_FILTER_EXAMPLE_FILES_REGEX  57349
#define IDS_URL_HELP                    57350
#define IDS_URL_REPORT_BUG              57351
#define IDS_URL_WEBSITE                 57352

#define ID_APP_ABOUT                    32768
#define ID_APP_EXIT                     32769
#define ID_CLEANUP_CREATE_HARDLINK      32770
#define ID_CLEANUP_DELETE               32771
#define ID_CLEANUP_DELETE_BIN           32772
#define ID_CLEANUP_DISK_CLEANUP         32773
#define ID_CLEANUP_DISM_ANALYZE         32774
#define ID_CLEANUP_DISM_NORMAL          32775
#define ID_CLEANUP_DISM_RESET           32776
#define ID_CLEANUP_EMPTY_BIN            32777
#define ID_CLEANUP_EMPTY_FOLDER         32778
#define ID_CLEANUP_EXPLORER_SELECT      32779
#define ID_CLEANUP_HIBERNATE            32780
#define ID_CLEANUP_MOVE_TO              32781
#define ID_CLEANUP_OPEN_IN_CONSOLE      32782
#define ID_CLEANUP_OPEN_IN_PWSH         32783
#define ID_CLEANUP_OPEN_SELECTED        32784
#define ID_CLEANUP_OPTIMIZE_VHD         32785
#define ID_CLEANUP_PROPERTIES           32786
#define ID_CLEANUP_REMOVE_EMPTY         32787
#define ID_CLEANUP_REMOVE_LOCAL         32788
#define ID_CLEANUP_REMOVE_MOTW          32789
#define ID_CLEANUP_REMOVE_PROGRAMS      32790
#define ID_CLEANUP_REMOVE_ROAMING       32791
#define ID_CLEANUP_REMOVE_SHADOW        32792
#define ID_CLEANUP_SPARSIFY_FILE        32793
#define ID_CLEANUP_STORAGE_SENSE        32794
#define ID_COMPRESS_NONE                32795
#define ID_COMPRESS_LZNT1               32796
#define ID_COMPRESS_XPRESS4K            32797
#define ID_COMPRESS_XPRESS8K            32798
#define ID_COMPRESS_XPRESS16K           32799
#define ID_COMPRESS_LZX                 32800
#define ID_COMPUTE_HASH                 32801
#define ID_CONFIGURE                    32802
#define ID_EDIT_COPY_CLIPBOARD          32803
#define ID_EXTLIST_SEARCH_EXTENSION     32804
#define ID_FILE_SELECT                  32805
#define ID_FILTER                       32806
#define ID_FILTER_EXCLUDE_ITEM          32807
#define ID_HELP_MANUAL                  32808
#define ID_HELP_REPORTBUG               32809
#define ID_LOAD_RESULTS                 32810
#define ID_POPUP_CANCEL                 32811
#define ID_POPUP_TOGGLE                 32812
#define ID_REFRESH_ALL                  32813
#define ID_REFRESH_SELECTED             32814
#define ID_RUN_ELEVATED                 32815
#define ID_SAVE_DUPLICATES              32816
#define ID_SAVE_PERMISSIONS             32817
#define ID_SAVE_RESULTS                 32818
#define ID_SCAN_RESUME                  32819
#define ID_SCAN_STOP                    32820
#define ID_SCAN_SUSPEND                 32821
#define ID_SEARCH                       32822
#define ID_TOOLS_CHKDSK_BASE            32823
#define ID_TOOLS_DEFRAG_BASE            32849
#define ID_TOOLS_PERMISSIONS            32875
#define ID_TOOLS_RECOVERY               32876
#define ID_TOOLS_SET_DATES              32877
#define ID_TOOLS_SHADOW_COPY_BASE       32878
#define ID_TOOLS_STORAGE_ANALYTICS      32904
#define ID_TOOLS_WATCHER                32905
#define ID_TREEMAP_LOGICAL_SIZE         32906
#define ID_TREEMAP_PHYSICAL_SIZE        32907
#define ID_TREEMAP_RESELECT_CHILD       32908
#define ID_TREEMAP_SELECT_PARENT        32909
#define ID_TREEMAP_SHOW_EXTENSIONS      32910
#define ID_TREEMAP_SHOW_FOLDER_FRAMES   32911
#define ID_TREEMAP_ZOOMIN               32912
#define ID_TREEMAP_ZOOMOUT              32913
#define ID_TREEMAP_ZOOMRESET            32914
#define ID_USERDEFINEDCLEANUP0          32915
#define ID_USERDEFINEDCLEANUP1          32916
#define ID_USERDEFINEDCLEANUP2          32917
#define ID_USERDEFINEDCLEANUP3          32918
#define ID_USERDEFINEDCLEANUP4          32919
#define ID_USERDEFINEDCLEANUP5          32920
#define ID_USERDEFINEDCLEANUP6          32921
#define ID_USERDEFINEDCLEANUP7          32922
#define ID_USERDEFINEDCLEANUP8          32923
#define ID_USERDEFINEDCLEANUP9          32924
#define ID_VIEW_ABSOLUTE_PERCENTAGES    32925
#define ID_VIEW_ALL_FILES               32926
#define ID_VIEW_DUPLICATE_FILES         32927
#define ID_VIEW_FLAMEGRAPH              32928
#define ID_VIEW_FONT_SIZE_100           32929
#define ID_VIEW_FONT_SIZE_125           32930
#define ID_VIEW_FONT_SIZE_150           32931
#define ID_VIEW_FONT_SIZE_175           32932
#define ID_VIEW_FONT_SIZE_200           32933
#define ID_VIEW_FONT_SIZE_USE_WINDOWS   32934
#define ID_VIEW_GRAPH_PRESET_CLASSIC    32935
#define ID_VIEW_GRAPH_PRESET_CALM       32936
#define ID_VIEW_GRAPH_PRESET_FLAT       32937
#define ID_VIEW_GRAPH_PRESET_PASTEL     32938
#define ID_VIEW_GRAPH_PRESET_HIGH_CONTRAST 32939
#define ID_VIEW_GRAPH_PRESET_CUSTOM     32940
#define ID_VIEW_GROUP_TYPES             32941
#define ID_VIEW_LARGEST_FILES           32942
#define ID_VIEW_SEARCH_RESULTS          32943
#define ID_VIEW_SHOWFILETYPES           32944
#define ID_VIEW_SHOWFREESPACE           32945
#define ID_VIEW_SHOWUNKNOWN             32946
#define ID_VIEW_SHOWVISUALIZATION       32947
#define ID_VIEW_SUNBURST                32948
#define ID_VIEW_TOOLBAR                 32949
#define ID_VIEW_STATUS_BAR              32950
#define ID_VIEW_TOOLBAR_SIZE_100        32951
#define ID_VIEW_TOOLBAR_SIZE_125        32952
#define ID_VIEW_TOOLBAR_SIZE_150        32953
#define ID_VIEW_TOOLBAR_SIZE_175        32954
#define ID_VIEW_TOOLBAR_SIZE_200        32955
#define ID_VIEW_TOOLBAR_SIZE_USE_WINDOWS 32956
#define ID_VIEW_TREEMAP_ROWS            32957
#define ID_VIEW_TREEMAP_SQUARIFIED      32958
#define ID_VIEW_TREEMAP_HILBERT         32959
#define ID_VIEW_TREEMAP_MOORE           32960
#define ID_VIEW_WINDOW_LAYOUT           32961
#define ID_WATCHER_AUTOSCROLL           32962
#define ID_WATCHER_CLEAR                32963
#define ID_WATCHER_FILTER               32964
#define ID_WATCHER_LABEL                32965
#define ID_WATCHER_PAUSE                32966
#define ID_WATCHER_START                32967
#define ID_WDS_CONTROL                  32968

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        119
#define _APS_NEXT_COMMAND_VALUE         32969
#define _APS_NEXT_CONTROL_VALUE         1176
#define _APS_NEXT_SYMED_VALUE           119
#endif
#endif
