//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by windirstat.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_PAGE_ADVANCED               102
#define IDR_MAINFRAME                   128
#define IDB_NODES                       131
#define IDD_SELECTDRIVES                133
#define IDR_POPUP_TREE                  134
#define IDR_POPUP_MAP                   136
#define IDR_LICENSE                     137
#define IDD_DELETE_WARNING              138
#define IDD_MODALAPISHUTTLE             140
#define IDD_PAGE_CLEANUPS               141
#define IDD_PAGE_TREELIST               142
#define IDD_PAGE_TREEMAP                143
#define IDD_PAGE_GENERAL                144
#define IDB_FILE_SELECT                 922
#define IDB_CLEANUP_DELETE_BIN          927
#define IDB_EDIT_COPY_CLIPBOARD         928
#define IDB_SCAN_SUSPEND                930
#define IDB_REFRESH_ALL                 931
#define IDB_CLEANUP_DELETE              932
#define IDB_SCAN_STOP                   933
#define IDB_TREEMAP_ZOOMOUT             934
#define IDB_CLEANUP_PROPERTIES          936
#define IDB_CLEANUP_OPEN_IN_CONSOLE     937
#define IDB_REFRESH_SELECTED            938
#define IDB_HELP_MANUAL                 939
#define IDB_SCAN_RESUME                 940
#define IDB_CLEANUP_EXPLORER_SELECT     941
#define IDB_CLEANUP_OPEN_SELECTED       942
#define IDI_JUNCTION                    943
#define IDI_UNKNOWN                     944
#define IDI_JUNCTION_PROTECTED          946
#define IDI_FREE_SPACE                  947
#define IDI_EMPTY                       948
#define IDC_ALLDRIVES                   1000
#define IDC_SOMEDRIVES                  1001
#define IDC_AFOLDER                     1002
#define IDC_DRIVES                      1005
#define IDC_TAB                         1013
#define IDC_CAPTION                     1014
#define IDC_DONTSHOWAGAIN               1017
#define IDC_PACMANANIMATION             1021
#define IDC_ASKFORCONFIRMATION          1022
#define IDC_SHOWTIMESPENT               1022
#define IDC_TREEMAPGRID                 1022
#define IDC_EXCLUDE_VOLUME_MOUNT_POINTS 1022
#define IDC_SHOWCONSOLEWINDOW           1023
#define IDC_TREECOL_OWNER               1023
#define IDC_WAITFORCOMPLETION           1024
#define IDC_TREECOL_FOLDERS             1024
#define IDC_TREECOL_LASTCHANGE          1025
#define IDC_TREECOL_ITEMS               1026
#define IDC_SHOW_GRID                   1028
#define IDC_TREECOL_FILES               1028
#define IDC_SIZE_SUFFIXES               1029
#define IDC_EXCLUDE_JUNCTIONS           1029
#define IDC_TREECOL_SIZE_PHYSICAL       1029
#define IDC_TREEMAPGRIDCOLOR            1030
#define IDC_SHOW_STRIPES                1030
#define IDC_EXCLUDE_SYMLINKS            1030
#define IDC_TREECOL_SIZE_LOGICAL        1030
#define IDC_FULL_ROW_SELECTION          1031
#define IDC_SKIPHIDDEN                  1032
#define IDC_PORTABLE_MODE               1032
#define IDC_BACKUP_RESTORE              1033
#define IDC_DELETION_WARNING            1033
#define IDC_RESET                       1034
#define IDC_PAGE_ADVANCED_SKIP_CLOUD_LINKS 1034
#define IDC_SKIPPROTECTED               1035
#define IDC_LIST                        1036
#define IDC_TITLE                       1037
#define IDC_COMMANDLINE                 1038
#define IDC_WORKSFORFILES               1039
#define IDC_WORKSFORDIRECTORIES         1040
#define IDC_WORKSFORDRIVES              1042
#define IDC_REFRESHPOLICY               1043
#define IDC_HELPBUTTON                  1044
#define IDC_ENABLED                     1045
#define IDC_RECURSEINTOSUBDIRECTORIES   1046
#define IDC_HINTSP                      1047
#define IDC_HINTSN                      1048
#define IDC_UP                          1049
#define IDC_DOWN                        1050
#define IDC_WORKSFORUNCPATHS            1051
#define IDC_COLORBUTTON0                1100
#define IDC_COLORBUTTON1                1101
#define IDC_COLORBUTTON2                1102
#define IDC_COLORBUTTON3                1103
#define IDC_COLORBUTTON4                1104
#define IDC_COLORBUTTON5                1105
#define IDC_COLORBUTTON6                1106
#define IDC_COLORBUTTON7                1107
#define IDC_SLIDER                      1200
#define IDC_TREEMAPHIGHLIGHTCOLOR       1202
#define IDC_COMBO                       1203
#define IDC_SIZEGRIPPER                 1208
#define IDC_SCALEFACTOR                 1209
#define IDC_HEIGHT                      1210
#define IDC_CUSHIONSHADING              1211
#define IDC_BRIGHTNESS                  1212
#define IDC_KDIRSTAT                    1213
#define IDC_SEQUOIAVIEW                 1214
#define IDC_PREVIEW                     1215
#define IDC_STATICBRIGHTNESS            1216
#define IDC_STATICCUSHIONSHADING        1217
#define IDC_STATICHEIGHT                1218
#define IDC_STATICSCALEFACTOR           1219
#define IDC_LIGHTSOURCE                 1220
#define IDC_USE_WDS_LOCALE              1225
#define IDC_COMBO_THREADS               1230
#define IDC_TREECOL_ATTRIBUTES          1231
#define IDC_BROWSE_FOLDER               1232
#define IDC_FILENAMES                   1233
#define IDC_SCAN_DUPLICATES             1234
#define ID_WDS_CONTROL                  4711
#define ID_CLEANUP_EXPLORER_SELECT      32774
#define ID_TREEMAP_ZOOMIN               32783
#define ID_TREEMAP_ZOOMOUT              32784
#define IDB_TREEMAP_ZOOMIN              32784
#define ID_TREEMAP_SELECT_PARENT        32785
#define ID_VIEW_SHOWTREEMAP             32792
#define ID_HELP_REPORTBUG               32796
#define ID_CLEANUP_OPEN_IN_CONSOLE      32808
#define ID_CLEANUP_DELETE_BIN           32809
#define ID_CLEANUP_DELETE               32810
#define ID_CONFIGURE                    32813
#define ID_HELP_MANUAL                  32814
#define ID_REFRESH_ALL                  32816
#define ID_REFRESH_SELECTED             32817
#define ID_CLEANUP_EMPTY_BIN            32818
#define ID_VIEW_SHOWFREESPACE           32819
#define ID_VIEW_SHOWUNKNOWN             32820
#define ID_VIEW_SHOWFILETYPES           32846
#define ID_USERDEFINEDCLEANUP0          32900
#define ID_USERDEFINEDCLEANUP1          32901
#define ID_USERDEFINEDCLEANUP2          32902
#define ID_USERDEFINEDCLEANUP3          32903
#define ID_USERDEFINEDCLEANUP4          32904
#define ID_USERDEFINEDCLEANUP5          32905
#define ID_USERDEFINEDCLEANUP6          32906
#define ID_USERDEFINEDCLEANUP7          32907
#define ID_USERDEFINEDCLEANUP8          32908
#define ID_USERDEFINEDCLEANUP9          32909
#define ID_DUMMY_USERDEFINEDCLEANUP     33005
#define ID_POPUP_CANCEL                 33008
#define ID_TREEMAP_RESELECT_CHILD       33011
#define ID_EDIT_COPY_CLIPBOARD          33013
#define ID_CLEANUP_OPEN_SELECTED        33015
#define ID_CLEANUP_PROPERTIES           33019
#define ID_POPUP_TOGGLE                 33023
#define ID_RUN_ELEVATED                 33027
#define ID_FILE_SELECT                  33030
#define ID_SCAN_SUSPEND                 33031
#define ID_SCAN_RESUME                  33032
#define ID_LOAD_RESULTS                 33037
#define ID_SAVE_RESULTS                 33038
#define ID_SCAN_STOP                    33039
#define ID_POPUP_IDS                    33040
#define ID_EXPLORER_MENU                33041
#define ID_COMPRESS_NONE                33046
#define ID_COMPRESS_LZNT1               33047
#define ID_COMPRESS_XPRESS4K            33048
#define ID_COMPRESS_XPRESS8K            33049
#define ID_COMPRESS_XPRESS16K           33050
#define ID_COMPRESS_LZX                 33051
#define IDS_AUTHOR_EMAIL                57345
#define IDS_URL_WEBSITE                 57346
#define IDS_URL_HELP                    57347
#define IDS_URL_REPORT_BUG              57348

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        954
#define _APS_NEXT_COMMAND_VALUE         33052
#define _APS_NEXT_CONTROL_VALUE         1235
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
