//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by windirstat.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_PAGE_ADVANCED               101
#define IDD_PAGE_FILTERING              102
#define IDD_SELECTDRIVES                103
#define IDD_MESSAGEBOX                  105
#define IDD_MODALAPISHUTTLE             106
#define IDD_PAGE_CLEANUPS               107
#define IDD_PAGE_TREELIST               108
#define IDD_PAGE_TREEMAP                109
#define IDD_PAGE_GENERAL                110
#define IDD_SEARCH                      111
#define IDD_PROGRESS                    112
#define IDD_PAGE_PROMPTS                113
#define IDR_MAINFRAME                   128
#define IDR_POPUP_TREE                  129
#define IDR_POPUP_MAP                   130
#define IDR_LICENSE                     131
#define IDB_NODES                       200
#define IDB_NODES_INVERT                201
#define IDB_FILTER                      202
#define IDB_FILE_SELECT                 203
#define IDB_SEARCH                      204
#define IDB_CLEANUP_DELETE_BIN          205
#define IDB_EDIT_COPY_CLIPBOARD         206
#define IDB_SCAN_SUSPEND                207
#define IDB_REFRESH_ALL                 208
#define IDB_CLEANUP_DELETE              209
#define IDB_SCAN_STOP                   210
#define IDB_TREEMAP_ZOOMOUT             211
#define IDB_TREEMAP_ZOOMIN              212
#define IDB_CLEANUP_PROPERTIES          213
#define IDB_CLEANUP_OPEN_IN_CONSOLE     214
#define IDB_REFRESH_SELECTED            215
#define IDB_HELP_MANUAL                 216
#define IDB_SCAN_RESUME                 217
#define IDB_CLEANUP_EXPLORER_SELECT     218
#define IDB_CLEANUP_OPEN_SELECTED       219
#define IDI_JUNCTION                    300
#define IDI_UNKNOWN                     301
#define IDI_JUNCTION_PROTECTED          302
#define IDI_FREE_SPACE                  303
#define IDI_EMPTY                       304
#define IDC_RADIO_TARGET_DRIVES_ALL     1000
#define IDC_RADIO_TARGET_DRIVES_SUBSET  1001
#define IDC_RADIO_TARGET_FOLDER         1002
#define IDC_TARGET_DRIVES_LIST          1003
#define IDC_TAB                         1004
#define IDC_CAPTION                     1005
#define IDC_PACMANANIMATION             1007
#define IDC_ASKFORCONFIRMATION          1008
#define IDC_SHOWTIMESPENT               1009
#define IDC_TREEMAPGRID                 1010
#define IDC_EXCLUDE_VOLUME_MOUNT_POINTS 1011
#define IDC_SHOWCONSOLEWINDOW           1012
#define IDC_TREECOL_OWNER               1013
#define IDC_WAITFORCOMPLETION           1014
#define IDC_TREECOL_FOLDERS             1015
#define IDC_TREECOL_LAST_CHANGE         1016
#define IDC_TREECOL_ITEMS               1017
#define IDC_SHOW_GRID                   1018
#define IDC_TREECOL_FILES               1019
#define IDC_SIZE_SUFFIXES               1020
#define IDC_TREECOL_SIZE_PHYSICAL       1021
#define IDC_EXCLUDE_JUNCTIONS           1022
#define IDC_TREEMAPGRIDCOLOR            1023
#define IDC_SHOW_STRIPES                1024
#define IDC_TREECOL_SIZE_LOGICAL        1025
#define IDC_EXCLUDE_SYMLINKS_DIRECTORY  1026
#define IDC_FULL_ROW_SELECTION          1027
#define IDC_PORTABLE_MODE               1028
#define IDC_EXCLUDE_HIDDEN_DIRECTORY    1029
#define IDC_BACKUP_RESTORE              1030
#define IDC_DELETION_WARNING            1031
#define IDC_RESET                       1032
#define IDC_SKIP_CLOUD_LINKS            1033
#define IDC_COLUMN_AUTOSIZE             1034
#define IDC_EXCLUDE_PROTECTED_DIRECTORY 1035
#define IDC_LIST                        1036
#define IDC_EXCLUDE_PROTECTED_FILE      1037
#define IDC_TITLE                       1038
#define IDC_EXCLUDE_SYMLINKS_FILE       1039
#define IDC_COMMANDLINE                 1040
#define IDC_EXCLUDE_HIDDEN_FILE         1041
#define IDC_WORKSFORFILES               1042
#define IDC_WORKSFORDIRECTORIES         1043
#define IDC_WORKSFORDRIVES              1044
#define IDC_REFRESHPOLICY               1045
#define IDC_HELPBUTTON                  1046
#define IDC_ENABLED                     1047
#define IDC_RECURSEINTOSUBDIRECTORIES   1048
#define IDC_HINTSP                      1049
#define IDC_HINTSN                      1050
#define IDC_UP                          1051
#define IDC_DOWN                        1052
#define IDC_WORKSFORUNCPATHS            1053
#define IDC_COLORBUTTON0                1054
#define IDC_COLORBUTTON1                1055
#define IDC_COLORBUTTON2                1056
#define IDC_COLORBUTTON3                1057
#define IDC_COLORBUTTON4                1058
#define IDC_COLORBUTTON5                1059
#define IDC_COLORBUTTON6                1060
#define IDC_COLORBUTTON7                1061
#define IDC_SLIDER                      1062
#define IDC_TREEMAPHIGHLIGHTCOLOR       1063
#define IDC_COMBO                       1064
#define IDC_SIZEGRIPPER                 1065
#define IDC_SCALEFACTOR                 1066
#define IDC_HEIGHT                      1067
#define IDC_CUSHIONSHADING              1068
#define IDC_BRIGHTNESS                  1069
#define IDC_KDIRSTAT                    1070
#define IDC_SEQUOIAVIEW                 1071
#define IDC_PREVIEW                     1072
#define IDC_STATICBRIGHTNESS            1073
#define IDC_STATICCUSHIONSHADING        1074
#define IDC_STATICHEIGHT                1075
#define IDC_STATICSCALEFACTOR           1076
#define IDC_LIGHTSOURCE                 1077
#define IDC_USE_WINDOWS_LOCALE          1078
#define IDC_COMBO_THREADS               1079
#define IDC_TREECOL_ATTRIBUTES          1080
#define IDC_BROWSE_FOLDER               1081
#define IDC_SCAN_DUPLICATES             1083
#define IDC_RESET_PREFERENCES           1084
#define IDC_FILTERING_EXCLUDE_DIRS      1085
#define IDC_FILTERING_EXCLUDE_FILES     1086
#define IDC_FILTERING_SIZE_MIN          1087
#define IDC_FILTERING_USE_REGEX         1088
#define IDC_FILTERING_MIN_UNITS         1089
#define IDC_LARGEST_FILE_COUNT          1090
#define IDC_FOLDER_HISTORY_COUNT        1091
#define IDC_SEARCH_REGEX                1091
#define IDC_SEARCH_CASE                 1092
#define IDC_SEARCH_TERM                 1093
#define IDC_SEARCH_WHOLE_PHRASE         1094
#define IDC_DARK_MODE_DISABLED          1095
#define IDC_DARK_MODE_USE_WINDOWS       1096
#define IDC_DARK_MODE_ENABLED           1097
#define IDC_FAST_SCAN_CHECKBOX          1098
#define IDC_MESSAGE_ICON                1099
#define IDC_MESSAGE_TEXT                1100
#define IDC_MESSAGE_BUTTONLEFT          1101
#define IDC_MESSAGE_BUTTONMIDDLE        1102
#define IDC_MESSAGE_BUTTONRIGHT         1103
#define IDC_MESSAGE_CHECKBOX            1104
#define IDC_MESSAGE_LISTVIEW            1105
#define IDC_BROWSE_BUTTON               1109
#define IDC_PROGRESS_MESSAGE            1110
#define IDC_PROGRESS_BAR                1111
#define IDC_ELEVATION_PROMPT            1112
#define IDC_FAST_SCAN_PROMPT            1113
#define IDC_CLOUD_LINKS_WARNING         1114
#define ID_WDS_CONTROL                  4711
#define ID_CLEANUP_EXPLORER_SELECT      32768
#define ID_TREEMAP_ZOOMIN               32769
#define ID_TREEMAP_ZOOMOUT              32770
#define ID_TREEMAP_SELECT_PARENT        32771
#define ID_VIEW_SHOWTREEMAP             32772
#define ID_HELP_REPORTBUG               32773
#define ID_CLEANUP_OPEN_IN_CONSOLE      32774
#define ID_CLEANUP_DELETE_BIN           32775
#define ID_CLEANUP_DELETE               32776
#define ID_FILTER                       32777
#define ID_SEARCH                       32778
#define ID_CONFIGURE                    32779
#define ID_HELP_MANUAL                  32780
#define ID_REFRESH_ALL                  32781
#define ID_REFRESH_SELECTED             32782
#define ID_CLEANUP_EMPTY_BIN            32783
#define ID_VIEW_SHOWFREESPACE           32784
#define ID_VIEW_SHOWUNKNOWN             32785
#define ID_VIEW_SHOWFILETYPES           32786
#define ID_USERDEFINEDCLEANUP0          32787
#define ID_USERDEFINEDCLEANUP1          32788
#define ID_USERDEFINEDCLEANUP2          32789
#define ID_USERDEFINEDCLEANUP3          32790
#define ID_USERDEFINEDCLEANUP4          32791
#define ID_USERDEFINEDCLEANUP5          32792
#define ID_USERDEFINEDCLEANUP6          32793
#define ID_USERDEFINEDCLEANUP7          32794
#define ID_USERDEFINEDCLEANUP8          32795
#define ID_USERDEFINEDCLEANUP9          32796
#define ID_POPUP_CANCEL                 32797
#define ID_TREEMAP_RESELECT_CHILD       32798
#define ID_EDIT_COPY_CLIPBOARD          32799
#define ID_CLEANUP_OPEN_SELECTED        32800
#define ID_CLEANUP_PROPERTIES           32801
#define ID_POPUP_TOGGLE                 32802
#define ID_RUN_ELEVATED                 32803
#define ID_FILE_SELECT                  32804
#define ID_SCAN_SUSPEND                 32805
#define ID_SCAN_RESUME                  32806
#define ID_LOAD_RESULTS                 32807
#define ID_SAVE_RESULTS                 32808
#define ID_SCAN_STOP                    32809
#define ID_COMPRESS_NONE                32810
#define ID_COMPRESS_LZNT1               32811
#define ID_COMPRESS_XPRESS4K            32812
#define ID_COMPRESS_XPRESS8K            32813
#define ID_COMPRESS_XPRESS16K           32814
#define ID_COMPRESS_LZX                 32815
#define ID_CLEANUP_DISK_CLEANUP         32816
#define ID_CLEANUP_DISM_NORMAL          32817
#define ID_CLEANUP_DISM_RESET           32818
#define ID_CLEANUP_REMOVE_ROAMING       32819
#define ID_CLEANUP_OPEN_IN_PWSH         32820
#define ID_INDICATOR_DISK               32821
#define ID_INDICATOR_MEM                32822
#define ID_INDICATOR_IDLE               32823
#define ID_CLEANUP_EMPTY_FOLDER         32824
#define ID_CLEANUP_HIBERNATE            32825
#define ID_TREEMAP_LOGICAL_SIZE         32826
#define ID_VIEW_ALL_FILES               32827
#define ID_VIEW_LARGEST_FILES           32828
#define ID_VIEW_DUPLICATE_FILES         32829
#define ID_VIEW_SEARCH_RESULTS          32830
#define ID_COMPUTE_HASH                 32832
#define ID_CLEANUP_REMOVE_LOCAL         32833
#define ID_CLEANUP_REMOVE_SHADOW        32834
#define ID_CLEANUP_DISM_ANALYZE         32835
#define ID_SAVE_DUPLICATES              32836
#define ID_AUTO_ELEVATE                 32837
#define ID_SHOWELEVATEPROMPT            32838
#define ID_SHOWUSEFASTSCANPROMPT        32839
#define IDS_AUTHOR_EMAIL                57345
#define IDS_URL_WEBSITE                 57346
#define IDS_URL_HELP                    57347
#define IDS_URL_REPORT_BUG              57348
#define IDS_FILTER_EXAMPLE_FILES        57349
#define IDS_FILTER_EXAMPLE_DIRS         57350
#define IDS_FILTER_EXAMPLE_FILES_REGEX  57351
#define IDS_FILTER_EXAMPLE_DIRS_REGEX   57352

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        305
#define _APS_NEXT_COMMAND_VALUE         32840
#define _APS_NEXT_CONTROL_VALUE         1112
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
