[%
pages = [
 {
   fname = 'background.html'
   title = 'Background'
   description = 'Background and history'
   uuid = '07c225cb-e2db-49da-b1d5-c33588c8ffbb'
   norder = '4000'
 }

 {
   fname = 'contact.html'
   title = 'Contact'
   description = 'Contact the team or a team member'
   uuid = 'a57cd25d-42ee-4e3a-aa24-f42b9548dbdd'
   norder = '9989'
 }

 {
   fname = 'download.html'
   title = 'Downloads, permalinks'
   description = 'Permalinks to downloads and other content'
   uuid = '8dccb375-74a0-4fde-a733-0019572b0646'
   norder = '1000'
 }

 {
   fname = 'index.html'
   title = 'Home'
   description = 'Windows Directory Statistics'
   uuid = '92e5b3ac-10ac-418e-97f9-8156b67c1d57'
   norder = '0000'
 }

 {
   fname = 'logo.html'
   title = 'Logos'
   description = 'Logos / icons'
   uuid = '51f50289-c61f-4cf7-ac07-fd236f442f39'
   norder = '9999'
 }

 {
   fname = 'translations.html'
   title = 'Translation Project'
   description = 'Translations of WinDirStat'
   uuid = '5da70447-d5f0-4895-8377-88f4a1ac8b3e'
   norder = '6000'
 }

 {
   fname = 'unicode.html'
   title = 'Notes on Unicode'
   description = 'Notes on Unicode - Why is Unicode relevant?'
   uuid = '18f81132-3a23-474c-9b64-ff066752cc21'
   norder = '7000'
 }


]
%]
